# Generated by Django 4.1.4 on 2022-12-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenfimail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='departure_date',
            field=models.DateTimeField(null=True),
        ),
    ]
