# Generated by Django 4.1.4 on 2022-12-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jenfimail', '0002_alter_shipment_departure_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcel',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='parcel',
            name='jenfimail_p_created_bd51b9_idx',
        ),
    ]
