# Generated by Django 4.1.4 on 2022-12-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenfimail', '0003_alter_parcel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='cost',
            field=models.FloatField(null=True),
        ),
    ]
