# Generated by Django 4.1.4 on 2022-12-12 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jenfimail', '0004_parcel_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='line',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='jenfimail.line'),
            preserve_default=False,
        ),
    ]
