# Generated by Django 4.1.4 on 2022-12-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jenfimail', '0005_shipment_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='available',
        ),
    ]
