# Generated by Django 4.1.4 on 2022-12-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenfimail', '0006_remove_line_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='arrival_date',
            field=models.DateTimeField(null=True),
        ),
    ]
