# Generated by Django 4.1.4 on 2022-12-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenfimail', '0008_alter_line_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='is_withdrawn',
        ),
        migrations.AddField(
            model_name='parcel',
            name='withdrawn_at',
            field=models.DateTimeField(null=True),
        ),
    ]
