# Generated by Django 4.1.4 on 2022-12-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenfimail', '0009_remove_parcel_is_withdrawn_parcel_withdrawn_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['weight', 'volume', 'withdrawn_at'], name='jenfimail_p_weight_7d60ee_idx'),
        ),
    ]
