# Generated by Django 4.1.4 on 2022-12-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenfimail', '0010_parcel_jenfimail_p_weight_7d60ee_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='optimized_cost_per_weight',
            field=models.FloatField(null=True),
        ),
    ]
